---
title: "Dashboard Carrera La Luz 2022"
subtile: "Actividad 1 - Métodos y Simulación Estadística"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#dcf1f2"
      fg: "#052729" 
      primary: "#17545e" 
      base_font:
        google: Sen
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(ggplot2)
library(paqueteMET)
library(dplyr)

data("CarreraLuz22")

  
Theme2 = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  # axis.text.y = element_blank(),
  axis.text = element_text( size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  
  strip.text = element_text(size=8),
  title =element_text(size=8, face='bold')
)# tamaño letra por grupos

# subsets-----------------------------------------------------------------------
#CarreraLuz22$sex[CarreraLuz22$sex == "M"]="Hombre"
#CarreraLuz22$sex[CarreraLuz22$sex == "F"]="Mujer"

#-------------------------------------------------------------------------------
CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Hombre")
CarreraLuz22F = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")

#-------------------------------------------------------------------------------
categorias= data.frame(table(CarreraLuz22$categoria))
colnames(categorias)=c("categoria", "conteo")

categorias <- categorias %>% 
  mutate(perc = `conteo` / sum(`conteo`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

#-------------------------------------------------------------------------------

promedio_ciudades = aggregate(CarreraLuz22$timerun/60,by=list(CarreraLuz22$categoria), FUN=mean)
colnames(promedio_ciudades)=c("categoria", "media")

A = subset(CarreraLuz22$timerun/60, CarreraLuz22$sex=="Hombre")
B = subset(CarreraLuz22$timerun/60, CarreraLuz22$sex=="Mujer")

```


Pagina 1
=======================================================================  
Column { data-width=40 }
-----------------------------------------------------------------------
### minimo  {.value-box}
```{r}
valueBox(value =paste(round(min(CarreraLuz22$timerun/60),1), "min"), 
         caption = "Tiempo mas Corto", 
         icon = "fa-solid fa-check", 
         color = "#61c990")
```

### maximo  {.value-box}
```{r}
valueBox(value =paste(round(max(CarreraLuz22$timerun/60),1), "min"), 
         caption = "Tiempo mas Largo", 
         icon = "fa-solid fa-xmark", 
         color = "#61c990")
```

### hombres  {.value-box}
```{r}
valueBox(value = paste(length(subset(CarreraLuz22$timerun, CarreraLuz22$sex=="Hombre")),"Hombres"), 
         caption = "Número de Hombres", 
         icon = "fa-people", 
         color = "#5475b3")


```


### mujeres  {.value-box}
```{r}
valueBox(value = paste(length(subset(CarreraLuz22$timerun, CarreraLuz22$sex=="Mujer")),"Mujeres"), 
         caption = "Número de Mujeres", 
         icon = "fa-people", 
         color = "#9a54b3")
```


### promedioh  {.value-box}
```{r}
valueBox(value = paste(round(mean(A),2),"min"), 
         caption = "Tiempo promedio de carrera en hombres", 
         icon = "  ", 
         color = "#5475b3")
```






### promediom  {.value-box}
```{r}
valueBox(value = paste(round(mean(B),2),"min"), 
         caption = "Tiempo promedio de carrera en mujeres", 
         icon = "  ", 
         color = "#9a54b3")
```




Column {data-width=350}
-----------------------------------------------------------------------

### Tiempo Promedio por Categoría

```{r}
ggplot(CarreraLuz22, aes(x = categoria, y = timerun/60, colour = sex)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter()+
  labs(title = "", y= "tiempo - min", x= "categoria")

```





Column {data-width=350}
-----------------------------------------------------------------------

### Histograma de Hombres  y Mujeres

```{r, echo=FALSE, out.width="30%", fig.align = "center"}

ggplot(CarreraLuz22, aes(x = timerun/60, fill = sex, colour = sex)) + 
  geom_histogram(alpha = 0.5, position = "identity") + 
  labs(title = "", y= "Frecuencia", x= "Tiempos")+
  theme(legend.position = "left")




```

### Participantes por Categoría
```{r, fig.height=3}


ggplot(categorias, aes(x = "", y = perc, fill = categoria)) +
  geom_col() +
  geom_label(aes(label = labels),
             position = position_stack(vjust = 0.5),
             show.legend = FALSE) +
  guides(fill = guide_legend(title = "Categoria")) +
  scale_fill_viridis_d() +
  coord_polar(theta = "y")+
  theme_void()





```

Pagina 2
=======================================================================  

Column {data-width=1000 .tabset}
-----------------------------------------------------------------------

### Tiempos de Hombres y Mujeres

```{r}
ggplot(CarreraLuz22, aes(x = sex, y = timerun/60 )) +
  geom_boxplot(aes(fill = sex)) + 
  # facet_wrap(~sex, ncol=1, labeller = labeller(dose = etiquetas))+
  labs(title = "", y= "tiempo - min", x= "sexo")+
  scale_fill_brewer() +
  #scale_fill_manual(values = c("#00070D", "#012447", "#034A94", "#0570E1", "#3998FB","#37B6FC"))+
  theme(legend.position = "none")

```

### Relacion Edad-Tiempo

```{r, fig.height=3}
ggplot(CarreraLuz22, aes(x = edad, y = timerun/60, color = sex)) +
  labs(title = "", y= "tiempo - min", x= "edad")+
  geom_point()

```

### Tiempo Hombres y Mujeres por Categoría

```{r}


ggplot(promedio_ciudades, aes(x = categoria, y = media, fill = categoria)) + 
  geom_bar(stat = "identity")+
  labs(title = "", y= "promedio", x= "categoria")+
  scale_fill_brewer()
  


```



